### ISSUE TITLE
Has WinUI publishing regressed for you?

### ISSUE THREAD

**Issue by BurkusCat** [Skuty/TrackYourDay#39]
Sorry for posting an issue on your project to ask you this. But searching GitHub I noticed you had a WinUI MAUI pipeline similar to mine. I've found that in the past few weeks my build has regressed (dotnet/maui/issues/20299).

I see that your last publish was three weeks ago which I think would have been before .NET 8.0.101 and .NET MAUI 8.0.6 releasing. I'd be curious to see if your next publish has any issues. Apologies again for posting an issue like this on your GitHub, potentially you won't have any issue, but if you do, hopefully I will have at least saved you some time debugging.

**Comment by Skuty** [comment]
Hey @BurkusCat 
No problem at all!
I didn't publish new Release after upgrading to NET 8 but I did a pre Release that is working. 

Indeed I was struggling with issue similar to the one that you are describing..

https://github.com/Skuty/TrackYourDay/compare/main...refactor-update-net-version-to-8, two last commits were the one that fixed the issue.

**Comment by BurkusCat** [comment]
Thanks @Skuty - your pipelines where you have split NuGet restore from build, led me to do the same thing. That is where I realised my issue was I was setting `RUNTIMEIDENTIFIER: win-x64` globally in my pipeline which caused all steps to use it even though I only wanted specific steps to use it. Removing that global variable resolved the issue for me and allowed me to create builds that outputted to the `win10-x64` folder. Thanks again! :)
